version: 2.1
orbs:
  architect: giantswarm/architect@4.0.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: "architect"
          # executor: "app-build-suite" # uncomment this if you want automatic metadata generation
          name: "package and push oms-agent chart"
          app_catalog: "giantswarm-playground-catalog"
          app_catalog_test: "giantswarm-playground-test-catalog"
          executor: "app-build-suite"
          chart: "oms-agent"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
