apiVersion: v1
kind: Secret
metadata:
  name: omsagent-secret
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  WSID: {{ .Values.omsagent.secret.wsid | b64enc | quote }}
  KEY: {{ .Values.omsagent.secret.key | b64enc | quote }}

