kind: Service
apiVersion: v1
metadata:
  name: healthmodel-replicaset-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    rsName: "omsagent-rs"
  ports:
    - protocol: TCP
      port: 25227
      targetPort: in-rs-tcp
